version: '1.0'
services: 
     mongodb: 
       image: mongo
       container_name: mongodb
       ports: 
         - "27017:27017"
       volumes: 
         - "mongodb_data:/data/db"
     youtube-clone-demo:
        # build: .
        image: "youtube-clone-demo"
        container_name: clone_app
        ports: 
          - 3000:3000
        # environment: 
          # - MONGO_URL: mongodb://mongodb:27017   

volumes: 
   mongodb_data: